### ISSUE TITLE
I'm facing install on Ubuntu 16.04 latest nightly Rust

### ISSUE THREAD

**Issue by ookangzheng** [jedisct1/edgedns#11] opened 2017-07-28 10:29 UTC
<img width="889" alt="screen shot 2017-07-28 at 18 29 03" src="https://user-images.githubusercontent.com/6301735/28713682-ba42c712-73c2-11e7-998d-11e0e1f5dd05.png">

Thanks

**Comment by jedisct1** [comment] 2017-07-28 16:36
Looks like a regression in the latest Cargo nightly!

**Comment by jedisct1** [comment] 2017-08-28 15:22
Prometheus was updated; this should be now fixed, thanks!

**Closed by jedisct1** 2017-08-28 15:22 UTC
